
MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 100

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

# .match?() was added in ruby 2.4
Performance/RegexpMatch:
  Enabled: false

## slow testing is oK
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
